name: Full DevOps Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permet de lancer le pipeline manuellement si besoin

jobs:
  # ==========================================
  # 1. PROVISIONNING INFRASTRUCTURE VIA TERRAFORM
  # ==========================================
  terraform:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    outputs:
      instance_ips: ${{ steps.export.outputs.instance_ips }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # TRÈS IMPORTANT pour AWS Academy
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Apply
        run: terraform apply -auto-approve 

      - name: Export Instance IPs
        id: export
        run: |
          IPS=$(terraform output -json instance_public_ips | jq -r '.[]' | tr '\n' ',' | sed 's/,$//')
          echo "instance_ips=$IPS" >> $GITHUB_OUTPUT

  # ==========================================
  # 2. CONFIGURATION DES SERVEURS VIA ANSIBLE
  # ==========================================
  ansible:
    name: Configure Servers
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible jq
          ansible-galaxy collection install amazon.aws

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Generate Inventory
        run: |
          echo "[web]" > inventory.ini
          for ip in $(echo "${{ needs.terraform.outputs.instance_ips }}" | tr ',' ' '); do
            echo "$ip ansible_user=ec2-user ansible_ssh_private_key_file=key.pem" >> inventory.ini
          done

      - name: Run Ansible Deployment
        run: |
          ansible-playbook -i inventory.ini ansible/deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
