name: Full DevOps Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permet de lancer le pipeline manuellement si besoin

jobs:
  # ==========================================
  # 1. NETTOYAGE DE L'INFRASTRUCTURE VIA TERRAFORM
  # ==========================================
  terraform:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    outputs:
      instance_ips: ${{ steps.export.outputs.instance_ips }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # TRÈS IMPORTANT pour AWS Academy
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # On remplace l'apply par un destroy temporaire pour vider le compte AWS
      - name: Terraform Destroy Nettoyage
        run: terraform destroy -auto-approve

      - name: Export Instance IPs
        id: export
        run: |
          echo "instance_ips=" >> $GITHUB_OUTPUT
